// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct Images {
        public let url: String
        public let altText: String?
        public let height: Int?
        public let width: Int?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(url: String, altText: String? = nil, height: Int? = nil, width: Int? = nil) {
            self.url = url
            self.altText = altText
            self.height = height
            self.width = width
        }
    }
}

extension Shared.Images: Codable {
    enum CodingKeys: String, CodingKey {
        case url
        case altText = "alt_text"
        case height
        case width
    }
}

