// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct MetaData {
        public let inferenceId: String?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(inferenceId: String? = nil) {
            self.inferenceId = inferenceId
        }
    }
}

extension Shared.MetaData: Codable {
    enum CodingKeys: String, CodingKey {
        case inferenceId = "inference_id"
    }
}

