// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct ProductCode {
        public let type: Shared.TypeModel?
        public let value: String?

        /// Creates an object with the specified parameters
        ///
        ///
        public init(type: Shared.TypeModel? = nil, value: String? = nil) {
            self.type = type
            self.value = value
        }
    }
}

extension Shared.ProductCode: Codable {
    enum CodingKeys: String, CodingKey {
        case type
        case value
    }
}

