// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A model object
    public struct SearchSimilarByItemResults {
        public let products: Shared.Products

        /// Creates an object with the specified parameters
        ///
        ///
        public init(products: Shared.Products) {
            self.products = products
        }
    }
}

extension Shared.SearchSimilarByItemResults: Codable {
    enum CodingKeys: String, CodingKey {
        case products
    }
}

