// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A request model
    public struct SneakersIdBatchRequest {
        /// The sneaker's listing id to be asociated with the array of images.
        public let listingId: String
        /// The sneaker's array of image URLs. Specify a maximum of 32 urls.
        public let urls: [String]
        /// The confidence threshold value.
        @DecimalSerialized
        public private(set) var confidenceThreshold: Double?
        /// User-defined flat object to be returned in the response.
        public let custom: [String: AnyValue]?
        /// A boolean flag for restrictive mode.
        public let restrictiveMode: Bool?
        /// Whether to include sneaker variants.
        public let variants: Bool?

        /// Creates a request model with the specified parameters
        ///
        /// - Parameter listingId: The sneaker's listing id to be asociated with the array of images.
        /// - Parameter urls: The sneaker's array of image URLs. Specify a maximum of 32 urls.
        /// - Parameter confidenceThreshold: The confidence threshold value.
        /// - Parameter custom: User-defined flat object to be returned in the response.
        /// - Parameter restrictiveMode: A boolean flag for restrictive mode.
        /// - Parameter variants: Whether to include sneaker variants.
        ///
        public init(listingId: String, urls: [String], confidenceThreshold: Double? = nil, custom: [String: AnyValue]? = nil, restrictiveMode: Bool? = nil, variants: Bool? = nil) {
            self.listingId = listingId
            self.urls = urls
            self._confidenceThreshold = DecimalSerialized<Double?>(wrappedValue: confidenceThreshold)
            self.custom = custom
            self.restrictiveMode = restrictiveMode
            self.variants = variants
        }
    }
}

extension Shared.SneakersIdBatchRequest: Codable {
    enum CodingKeys: String, CodingKey {
        case listingId = "listing_id"
        case urls
        case confidenceThreshold = "confidence_threshold"
        case custom
        case restrictiveMode = "restrictive_mode"
        case variants
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.listingId = try container.decode(String.self, forKey: .listingId)
        self.urls = try container.decode([String].self, forKey: .urls)
        self._confidenceThreshold = try container.decodeIfPresent(DecimalSerialized<Double?>.self, forKey: .confidenceThreshold) ?? DecimalSerialized<Double?>(wrappedValue: nil)
        self.custom = try container.decodeIfPresent([String: AnyValue].self, forKey: .custom)
        self.restrictiveMode = try container.decodeIfPresent(Bool.self, forKey: .restrictiveMode)
        self.variants = try container.decodeIfPresent(Bool.self, forKey: .variants)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.listingId, forKey: .listingId)
        try container.encode(self.urls, forKey: .urls)
        if self.confidenceThreshold != nil {
            try container.encode(self._confidenceThreshold, forKey: .confidenceThreshold)
        }
        try container.encodeIfPresent(self.custom, forKey: .custom)
        try container.encodeIfPresent(self.restrictiveMode, forKey: .restrictiveMode)
        try container.encodeIfPresent(self.variants, forKey: .variants)
    }
}

extension Shared.SneakersIdBatchRequest {
    var confidenceThresholdWrapper: DecimalSerialized<Double?> {
        return _confidenceThreshold
    }
}
