// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Shared {
    /// A request model
    public struct SneakersIdAsyncRequest {
        /// The URL to which the webhook will be delivered once the identification process is completed.
        public let postbackUrl: String
        /// The sneaker's image URL.
        public let url: String
        /// The confidence threshold value.
        @DecimalSerialized
        public private(set) var confidenceThreshold: Double?
        /// User-defined flat object to be returned in the response.
        public let custom: [String: AnyValue]?
        /// A boolean flag for restrictive mode.
        public let restrictiveMode: Bool?

        /// Creates a request model with the specified parameters
        ///
        /// - Parameter postbackUrl: The URL to which the webhook will be delivered once the identification process is completed.
        /// - Parameter url: The sneaker's image URL.
        /// - Parameter confidenceThreshold: The confidence threshold value.
        /// - Parameter custom: User-defined flat object to be returned in the response.
        /// - Parameter restrictiveMode: A boolean flag for restrictive mode.
        ///
        public init(postbackUrl: String, url: String, confidenceThreshold: Double? = nil, custom: [String: AnyValue]? = nil, restrictiveMode: Bool? = nil) {
            self.postbackUrl = postbackUrl
            self.url = url
            self._confidenceThreshold = DecimalSerialized<Double?>(wrappedValue: confidenceThreshold)
            self.custom = custom
            self.restrictiveMode = restrictiveMode
        }
    }
}

extension Shared.SneakersIdAsyncRequest: Codable {
    enum CodingKeys: String, CodingKey {
        case postbackUrl = "postback_url"
        case url
        case confidenceThreshold = "confidence_threshold"
        case custom
        case restrictiveMode = "restrictive_mode"
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.postbackUrl = try container.decode(String.self, forKey: .postbackUrl)
        self.url = try container.decode(String.self, forKey: .url)
        self._confidenceThreshold = try container.decodeIfPresent(DecimalSerialized<Double?>.self, forKey: .confidenceThreshold) ?? DecimalSerialized<Double?>(wrappedValue: nil)
        self.custom = try container.decodeIfPresent([String: AnyValue].self, forKey: .custom)
        self.restrictiveMode = try container.decodeIfPresent(Bool.self, forKey: .restrictiveMode)
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.postbackUrl, forKey: .postbackUrl)
        try container.encode(self.url, forKey: .url)
        if self.confidenceThreshold != nil {
            try container.encode(self._confidenceThreshold, forKey: .confidenceThreshold)
        }
        try container.encodeIfPresent(self.custom, forKey: .custom)
        try container.encodeIfPresent(self.restrictiveMode, forKey: .restrictiveMode)
    }
}

extension Shared.SneakersIdAsyncRequest {
    var confidenceThresholdWrapper: DecimalSerialized<Double?> {
        return _confidenceThreshold
    }
}
