// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum CatalogSearchResponse {
        case empty
        case twoHundredApplicationJsonSearchResults([Shared.SearchResult])
        case fourHundredApplicationJsonObject(Operations.CatalogSearchResponseBody)
        case fourHundredAndThreeApplicationJsonObject(Operations.CatalogSearchSearchResponseBody)
        case fiveHundredApplicationJsonObject(Operations.CatalogSearchSearchResponseResponseBody)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func twoHundredApplicationJsonSearchResults() throws -> [Shared.SearchResult] {
            guard case .twoHundredApplicationJsonSearchResults(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fourHundredApplicationJsonObject() throws -> Operations.CatalogSearchResponseBody {
            guard case .fourHundredApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fourHundredAndThreeApplicationJsonObject() throws -> Operations.CatalogSearchSearchResponseBody {
            guard case .fourHundredAndThreeApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fiveHundredApplicationJsonObject() throws -> Operations.CatalogSearchSearchResponseResponseBody {
            guard case .fiveHundredApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }
    }
}
