// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// Successfully added item to catalog
    public struct CatalogItemAddResponseBody {
        /// The status of the the operation.
        public let status: String?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter status: The status of the the operation.
        ///
        public init(status: String? = nil) {
            self.status = status
        }
    }
}

extension Operations.CatalogItemAddResponseBody: Codable {
    enum CodingKeys: String, CodingKey {
        case status
    }
}

