// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// Successfully updated catalog item
    public struct CatalogItemUpdateResponseBody {
        /// The status of the the operation.
        public let status: Operations.CatalogItemUpdateStatus?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter status: The status of the the operation.
        ///
        public init(status: Operations.CatalogItemUpdateStatus? = nil) {
            self.status = status
        }
    }
}

extension Operations.CatalogItemUpdateResponseBody: Codable {
    enum CodingKeys: String, CodingKey {
        case status
    }
}

