// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum CatalogItemAddResponse {
        case empty
        case twoHundredApplicationJsonObject(Operations.CatalogItemAddResponseBody)
        case fourHundredApplicationJsonObject(Operations.CatalogItemAddCatalogResponseBody)
        case fourHundredAndThreeApplicationJsonObject(Operations.CatalogItemAddCatalogResponseResponseBody)
        case fiveHundredApplicationJsonObject(Operations.CatalogItemAddCatalogResponse500ResponseBody)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func twoHundredApplicationJsonObject() throws -> Operations.CatalogItemAddResponseBody {
            guard case .twoHundredApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fourHundredApplicationJsonObject() throws -> Operations.CatalogItemAddCatalogResponseBody {
            guard case .fourHundredApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fourHundredAndThreeApplicationJsonObject() throws -> Operations.CatalogItemAddCatalogResponseResponseBody {
            guard case .fourHundredAndThreeApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fiveHundredApplicationJsonObject() throws -> Operations.CatalogItemAddCatalogResponse500ResponseBody {
            guard case .fiveHundredApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }
    }
}
