// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// The status of the the operation.
    public enum CatalogItemUpdateStatus: String, Codable, APIValue {
        case success = "success"
    }
}
