// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct CatalogSearchRequest: APIValue {
        /// The text query.
        public let query: String
        /// The maximum number of results to return.
        @DecimalSerialized
        public private(set) var limit: Double?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter query: The text query.
        /// - Parameter limit: The maximum number of results to return.
        ///
        public init(query: String, limit: Double? = nil) {
            self.query = query
            self._limit = DecimalSerialized<Double?>(wrappedValue: limit)
        }
    }
}
extension Operations.CatalogSearchRequest {
    var limitWrapper: DecimalSerialized<Double?> {
        return _limit
    }
}
