// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// The status of the item.
    public enum Status: String, Codable, APIValue {
        case active = "active"
        case inactive = "inactive"
        case deleted = "deleted"
    }
}
