// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum ProductDataResponse {
        case empty
        case fourHundredApplicationJsonObject(Operations.ProductDataResponseBody)
        case fourHundredAndThreeApplicationJsonObject(Operations.ProductDataSearchResponseBody)
        case fiveHundredApplicationJsonObject(Operations.ProductDataSearchResponseResponseBody)
        case productWithUUID(Shared.ProductWithUUID)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func fourHundredApplicationJsonObject() throws -> Operations.ProductDataResponseBody {
            guard case .fourHundredApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fourHundredAndThreeApplicationJsonObject() throws -> Operations.ProductDataSearchResponseBody {
            guard case .fourHundredAndThreeApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fiveHundredApplicationJsonObject() throws -> Operations.ProductDataSearchResponseResponseBody {
            guard case .fiveHundredApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func productWithUUID() throws -> Shared.ProductWithUUID {
            guard case .productWithUUID(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }
    }
}
