// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A model object
    public struct ProductDataRequest: APIValue {
        /// The internal product id.
        public let productId: String
        /// The inference id.
        public let inferenceId: String?

        /// Creates an object with the specified parameters
        ///
        /// - Parameter productId: The internal product id.
        /// - Parameter inferenceId: The inference id.
        ///
        public init(productId: String, inferenceId: String? = nil) {
            self.productId = productId
            self.inferenceId = inferenceId
        }
    }
}
