// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum SimilarByItemResponse {
        case empty
        case fourHundredApplicationJsonObject(Operations.SimilarByItemResponseBody)
        case fourHundredAndThreeApplicationJsonObject(Operations.SimilarByItemSearchResponseBody)
        case fiveHundredApplicationJsonObject(Operations.SimilarByItemSearchResponseResponseBody)
        case searchSimilarByItemResults(Shared.SearchSimilarByItemResults)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func fourHundredApplicationJsonObject() throws -> Operations.SimilarByItemResponseBody {
            guard case .fourHundredApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fourHundredAndThreeApplicationJsonObject() throws -> Operations.SimilarByItemSearchResponseBody {
            guard case .fourHundredAndThreeApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fiveHundredApplicationJsonObject() throws -> Operations.SimilarByItemSearchResponseResponseBody {
            guard case .fiveHundredApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func searchSimilarByItemResults() throws -> Shared.SearchSimilarByItemResults {
            guard case .searchSimilarByItemResults(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }
    }
}
