// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// Successfully queued inference
    public struct SneakerIdBatchAsyncResponseBody {
        public let id: String
        public let internalId: String

        /// Creates an object with the specified parameters
        ///
        ///
        public init(id: String, internalId: String) {
            self.id = id
            self.internalId = internalId
        }
    }
}

extension Operations.SneakerIdBatchAsyncResponseBody: Codable {
    enum CodingKeys: String, CodingKey {
        case id
        case internalId = "internal_id"
    }
}

