// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum SneakerIdBatchAsyncResponse {
        case empty
        case twoHundredApplicationJsonObject(Operations.SneakerIdBatchAsyncResponseBody)
        case fourHundredApplicationJsonObject(Operations.SneakerIdBatchAsyncInferenceResponseBody)
        case fourHundredAndThreeApplicationJsonObject(Operations.SneakerIdBatchAsyncInferenceResponseResponseBody)
        case fiveHundredApplicationJsonObject(Operations.SneakerIdBatchAsyncInferenceResponse500ResponseBody)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func twoHundredApplicationJsonObject() throws -> Operations.SneakerIdBatchAsyncResponseBody {
            guard case .twoHundredApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fourHundredApplicationJsonObject() throws -> Operations.SneakerIdBatchAsyncInferenceResponseBody {
            guard case .fourHundredApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fourHundredAndThreeApplicationJsonObject() throws -> Operations.SneakerIdBatchAsyncInferenceResponseResponseBody {
            guard case .fourHundredAndThreeApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fiveHundredApplicationJsonObject() throws -> Operations.SneakerIdBatchAsyncInferenceResponse500ResponseBody {
            guard case .fiveHundredApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }
    }
}
