// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

import Foundation

extension Operations {
    /// A response model
    public enum SneakerIdResponse {
        case empty
        case twoHundredApplicationJsonObject(Operations.SneakerIdResponseBody)
        case fourHundredApplicationJsonObject(Operations.SneakerIdInferenceResponseBody)
        case fourHundredAndThreeApplicationJsonObject(Operations.SneakerIdInferenceResponseResponseBody)
        case fiveHundredApplicationJsonObject(Operations.SneakerIdInferenceResponse500ResponseBody)

        var isEmpty: Bool {
            if case .empty = self {
                return true
            } else {
                return false
            }
        }

        public func twoHundredApplicationJsonObject() throws -> Operations.SneakerIdResponseBody {
            guard case .twoHundredApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fourHundredApplicationJsonObject() throws -> Operations.SneakerIdInferenceResponseBody {
            guard case .fourHundredApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fourHundredAndThreeApplicationJsonObject() throws -> Operations.SneakerIdInferenceResponseResponseBody {
            guard case .fourHundredAndThreeApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }

        public func fiveHundredApplicationJsonObject() throws -> Operations.SneakerIdInferenceResponse500ResponseBody {
            guard case .fiveHundredApplicationJsonObject(let value) = self else {
                throw VenariAIError.missingResponseData
            }
            return value
        }
    }
}
